# docker-compose.yml

version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      DATABASE_URL: "pgsql://symfony:symfony@db:5432/symfony"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
